# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on:
  push:
    branches: [ main ]
    tags-ignore:
      - "pages-bot-page-build"
    

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [15.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/
    steps:
    - uses: actions/checkout@v2
      
    - name: Setup Git
      run: |
          git config user.name "Github Pages Builder Bot"
          git config user.email "<>"
          git checkout -B pages
      
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
      
    - name: Build Page
      run: yarn run ci
    
    - name: Store Built Page
      run: |
          # Stage the file, commit and push
          git add .
          git commit -m "pages bot: building page $(date)"
          git tag "pages-bot-page-build"
          git push origin pages
